/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KonfirmasiRouteImport } from './routes/konfirmasi'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as RekeningRouteImport } from './routes/rekening'
import { Route as WhyOpenbookRouteImport } from './routes/why-openbook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfirmasiRoute = KonfirmasiRouteImport.update({
  id: '/konfirmasi',
  path: '/konfirmasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const RekeningRoute = RekeningRouteImport.update({
  id: '/rekening',
  path: '/rekening',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyOpenbookRoute = WhyOpenbookRouteImport.update({
  id: '/why-openbook',
  path: '/why-openbook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/partner': typeof PartnerRoute
  '/program': typeof ProgramRoute
  '/rekening': typeof RekeningRoute
  '/why-openbook': typeof WhyOpenbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/partner': typeof PartnerRoute
  '/program': typeof ProgramRoute
  '/rekening': typeof RekeningRoute
  '/why-openbook': typeof WhyOpenbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/partner': typeof PartnerRoute
  '/program': typeof ProgramRoute
  '/rekening': typeof RekeningRoute
  '/why-openbook': typeof WhyOpenbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/faq'
    | '/konfirmasi'
    | '/partner'
    | '/program'
    | '/rekening'
    | '/why-openbook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/faq'
    | '/konfirmasi'
    | '/partner'
    | '/program'
    | '/rekening'
    | '/why-openbook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/faq'
    | '/konfirmasi'
    | '/partner'
    | '/program'
    | '/rekening'
    | '/why-openbook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  FaqRoute: typeof FaqRoute
  KonfirmasiRoute: typeof KonfirmasiRoute
  PartnerRoute: typeof PartnerRoute
  ProgramRoute: typeof ProgramRoute
  RekeningRoute: typeof RekeningRoute
  WhyOpenbookRoute: typeof WhyOpenbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfirmasi': {
      id: '/konfirmasi'
      path: '/konfirmasi'
      fullPath: '/konfirmasi'
      preLoaderRoute: typeof KonfirmasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekening': {
      id: '/rekening'
      path: '/rekening'
      fullPath: '/rekening'
      preLoaderRoute: typeof RekeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-openbook': {
      id: '/why-openbook'
      path: '/why-openbook'
      fullPath: '/why-openbook'
      preLoaderRoute: typeof WhyOpenbookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  FaqRoute: FaqRoute,
  KonfirmasiRoute: KonfirmasiRoute,
  PartnerRoute: PartnerRoute,
  ProgramRoute: ProgramRoute,
  RekeningRoute: RekeningRoute,
  WhyOpenbookRoute: WhyOpenbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
